### ISSUE TITLE
With invalid project collection address logged in successfully message

### ISSUE THREAD

**Issue by alkampfergit** [Microsoft/tfs-cli#13]
Here is a piece of a session, as you can see I've specified an invalid url, and typed random chars for password, but I still got a logged in successfully message. I think that the tool does not detect when the collection url is invalid.

PS C:\WINDOWS\system32> tfx login --authtype basic
Copyright Microsoft Corporation

Enter collection url > http://pippo.com
Enter username > alkampfer
Enter password >
logged in successfully

**Comment by bryanmacfarlane** [comment]
Do you have a recent version?  This was fixed a little while ago

https://github.com/Microsoft/tfs-cli/commit/81fea247716d52e2862d1bab7603f26075dc5e52

But I'll try again to verify

**Comment by bryanmacfarlane** [comment]
I see what the issue is.  If I type valid url but invalid creds, it catches it.  bad url + bad creds is not caught

-=B=- ~/Projects/Agent.Xplat$ tfx login
Copyright Microsoft Corporation

Enter collection url > https://bryanmac.visualstudio.com
Enter personal access token > 
Error: Invalid credentials

-=B=- ~/Projects/Agent.Xplat$ tfx login --authtype basic
Copyright Microsoft Corporation

Enter collection url > https://bryanmac.visualstudio.com
Enter username > asdf
Enter password > 
Error: Invalid credentials

-=B=- ~/Projects/Agent.Xplat$ tfx login --authtype basic
Copyright Microsoft Corporation

Enter collection url > http://wrongurl.com
Enter username > asdf
Enter password > 
logged in successfully

-=B=- ~/Projects/Agent.Xplat$

**Comment by alkampfergit** [comment]
exactly, it happens only if you specify an invalid project collection. It is surely a minor issue, but it is annoying because you think everything is ok then whatever further command you issue will fail.

**Comment by teddyward** [comment]
thanks for this! wasn't catching all errors... also would have given successful login if your internet was unplugged and probably a slew of other things.
