### ISSUE TITLE
TFX-CLI does not install on OSX

### ISSUE THREAD

**Issue by kashzonal** [microsoft/tfs-cli#147]
NPM fails to install the package on OSX, I have been able to install it on a Windows machine.

[npm-debug.log.zip](https://github.com/Microsoft/tfs-cli/files/481952/npm-debug.log.zip)

**Comment by AnnaOpareva** [comment]
Hi, @kashzonal Is it still an actual issue for you?

**Comment by AnnaOpareva** [comment]
Hi, @kashzonal, again. Is it still an actual issue for you?

**Comment by AnnaOpareva** [comment]
I have checked the installation of tfx-cli on mac and it is working as expected. This issue usually happens when your app package has the same name as the package that you are trying to install (here is an example https://stackoverflow.com/questions/42167754/refusing-to-install-twilio-as-a-dependency-of-itself). So let me close it for now since there is no issue with tfx-cli.
