### ISSUE TITLE
Overwrite option not working with tfx build tasks upload

### ISSUE THREAD

**Issue by cltshivash** [Microsoft/tfs-cli#208]
Expectation
------------
tfx build tasks upload --overwrite option should update the specified task.

Actual
-------
The task upload with overwrite option fails. See an example below. It makes development experience very painful.

c:\vststasks\Tasks>tfx build tasks upload --task-path ./RunLoadTest --overwrite
TFS Cross Platform Command Line Interface v0.3.49
Copyright Microsoft Corporation
error: Error: Failed Request: Conflict(409) - The task definition with id '9e9db
38a-b40b-4c13-b7f0-31031c894c22', name 'CloudLoadTest' and version '1.0.19' alre
ady exists.

**Comment by TsuyoshiUshio** [comment]
The same for me 

```
$ tfx build tasks upload --overwrite true --task-path .
TFS Cross Platform Command Line Interface v0.4.9
Copyright Microsoft Corporation
error: Error: Failed Request: Conflict(409) - The task definition with id '4bbc6ca0-59b2-11e7-83fe-c360e4fd66d4', name 'downloader' and version '0.1.1' already exists.

```

I tried to fix it. It might happen on the RestAPI. However, I can't find the spec or source code for the rest api. Do you know where it is?

**Comment by lucalandi** [comment]
Same problem here. To get all the possible commands I used the following dockerfile:
`FROM node:8.9.3
ENV TFX_TRACE 1
USER root
RUN npm i -g tfx-cli
RUN tfx --help ; tfx extension --help ; tfx extension resources --help ; tfx extension publish --help ; tfx extension create --help ; tfx build --help ; tfx build tasks --help ; tfx build tasks upload --help ; tfx build tasks list --help`
The tfx extension publish is apparently uploading only the first task available in the tasks folder. In my specific case I have 2 tasks to upload within an extension. To upload all the tasks I have a for loop that goes into all the tasks folders and performs a tfx tasks upload:
`RUN for t in $(find $PWD/Tasks -type d -mindepth 1 -maxdepth 1); do echo "---------------------- Uploading task: "${t}; tfx build tasks upload --task-path ${t} --overwrite --service-url https://account.visualstudio.com/DefaultCollection --token $ACCESS_TOKEN --json --trace-level debug; done`
When it tries to upload the first task it fails with a Conflict because the first task gets automatically uploaded with the extension publish:
`RUN tfx extension publish --manifest-globs vss-extension.json --share-with jet-tfs --token $ACCESS_TOKEN --no-prompt --json`
Not sure how to solve this problem. All I want is to have a sync between whatever I have in my private repo and the tasks belonging to my extension.

**Comment by bryanmacfarlane** [comment]
You can't overwrite our in the box tasks.  tfx upload was meant for your tasks as a dev tool.  We deploy and service our in the box tasks

**Comment by lucalandi** [comment]
Thanks a lot for the info. In my specific case I have only private tasks and intend to keep the extension private. When I publish the extension I see only the first task being updated but not the second in the list. When I run the tfx extension create I can clearly see that it builds both tasks. Should I open a separate issue for that ?

**Comment by bryanmacfarlane** [comment]
Tasks have independent versions.  Are you bumping the task version in task.json (only when you change it)?

Individual task versions are immutable.  If it doesn't change, it doesn't flow through the system (agent will cache tasks by id and version)

**Comment by bryanmacfarlane** [comment]
also vsts-task-lib is a better repo for issues ...
