### ISSUE TITLE
tfx cannot handle TLS certificate issued by corp certificate authority

### ISSUE THREAD

**Issue by VladimirKhvostov** [microsoft/tfs-cli#419]
tfx cannot handle TLS certificate issued by corp certificate authority, which are often used by on-premises Azure DevOps Server.
Are simple repro for engineers having access to MSFT corpnet would be to try connecting to the pioneer-new-dt or vstfdevdiv

Example of failure:
```
C:\Temp>tfx login
2022-11-08T15:32:21.476Z : loader.load
TFS Cross Platform Command Line Interface v0.12.0
Copyright Microsoft Corporation
> Service URL: https://pioneer-new-dt/VSTSDF
> Personal access token:
error: Error: Connection failed. Check your internet connection & collection URL.
error: Message: unable to get local issuer certificate
```

**Comment by DmitriiBobreshev** [comment]
Hi @VladimirKhvostov, thank you for reporting, the problem exists, but to implement this feature we need to fix it in [typed-rest-client](https://github.com/microsoft/typed-rest-client) because now it does not provide an option to pass [rejectUnauthorized](https://nodejs.org/api/https.html) to the request, as a temporary solution you can set [NODE_TLS_REJECT_UNAUTHORIZED=0](https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue) environment variable to skip certificate validation for TLS connections

**Comment by gitnubster** [comment]
If the corporate certificate can be fetched as a pem file, you can use this environment variable.
setx /m NODE_EXTRA_CA_CERTS=<full.path.to.cert.pem>
Tfx-cli should listen to that as it is build for node. See https://nodejs.org/api/cli.html#node_extra_ca_certsfile and https://stackoverflow.com/questions/70198705/how-can-i-set-node-extra-ca-certs-on-node
Don't forget to restart the devops agent (to reload environment setting you've just added). Reboot should always work.

**Comment by LiliaSabitova** [comment]
Hi @VladimirKhvostov, relevant PR has been merged and new release is already available.
Could you please check and advise whether issue is resolved for you?

**Comment by LiliaSabitova** [comment]
Hi @VladimirKhvostov, I'm closing the ticket since the issue should be resolved now.
Please feel free to re-open it if needed.
