### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by kasajian** [Microsoft/tfs-cli#68]
Could we get a list of Milestones for this project?  The reason is because the REST API for TFS / online is vast, and although it would be ideal to have this tool support every aspect of that API, reality is that the team here will likely only add support for highest priority features.

What I would like to know are;
* Are there any aspects of the REST API that simply are not part of the future/long-term plan of this project?   That is, you don't even wants us asking about it because it's simply not part of the chatter.
* Which APIs are slated to be supported next?
* Would it possible to off-load some of this work to the community?   If so, I would prefer the design/development be split into separate issues and tracked individually that way we can have those are more familiar with the design architecture to specify what the CLI API would be like, but we can have others in the community attempt to do the implementation.

For someone may be willing to implement work-item updating, or test management interface could if they 1) knew whether it was even part of the roadmap and 2) what would command-line interface look like.

**Comment by trevorsg** [comment]
Hi kasajian,

There are no official roadmaps or milestones for this project, unfortunately. I am all for anyone in the community contributing new features. I have been leaving open feature requests in Issues, and anyone can feel free to take those on. I would be happy to personally field any questions about implementation.

Different VSTS teams may have a different vested interest in this tool. For example, my team relies on it for Extensions development, which is why I have put a lot of work into the extensions commands. Community feedback is a great way to get an idea of which commands should be prioritized.

**Comment by kasajian** [comment]
Trevor, that's a fair response.   thank you.

**Comment by bryanmacfarlane** [comment]
The good news is the vso-node-api is generated so it's easy to get coverage there.  The cli can grow as needed
