### ISSUE TITLE
tfx extension / differences from VSET

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/tfs-cli#75]
**Missing/changed**
1. `VSET package` (not tfx extension create, which makes me think it's going to seed a new, empty extension for me)
2. `VSET package -m xxx.json` (have to specify --manifest-globs, which is about the longest command line argument name ever)

**Hmmm**
1. tfx extension create has `publisher` and `extension-id` ... both should end with `-in` or neither should.

**Comment by trevorsg** [comment]
1. I could rename tfx extension create to tfx extension package, and just deprecate "create" for now.
2. Get over it ;) (or use the handy-dandy --save feature!)

Hmm.1. They correspond to manifest properties - two common properties that are overridden (this supports the scenario of publishing a sample extension without having to modify it). There is a "publisher" and an "id" property. Since --id is not very descriptive, it became --extension-id. What is your suggestion for these?
